self-hosted-runner:
  labels:
    - linux_amd64
    - debian-13

config-variables: null

paths:
  .gitea/workflows/**/*.yml:
    ignore:
      - 'unknown permission scope "(code|releases)"'
      - 'the runner of "actions/(upload|download)-artifact@v3" action is too old to run on GitHub Actions'
