fallback = """
[agent]
"""

claude = """
 ▐▛███▜▌
▝▜█████▛▘
  ▘▘ ▝▝
"""

codex = """
 ▗▛███▜▖
▐▜▌ ▚ ▐▛▌
 ▝▀▀▀▀▀▘
"""

pi = """
 █▜███▛█
▝▜▛▀▀▀▜▛▘
 ▝▘   ▝▘
"""

opencode = """
 ▗▛▀▀▀▜▖
▝▜▌ █ ▐▛▘
 ▝▀▀▀▀▀▘
"""
