claude = """
 ▐▛███▜▌
▝▜█████▛▘
  ▘▘ ▝▝
"""

codex = """
 ▗▛▀▀▀▜▖
▐█ ▜▖  █▌
 ▝▀▀▀▀▀▘
"""

amp = """
 ▂▐███▌▂
▐█ ▮ ▮ █▌
 ▝▀▀▀▀▀▘
"""

pi = """
 █▜███▛█
▝▜▛▀▀▀▜▛▘
 ▝▘   ▝▘
"""

opencode = """
 ▗▛▀▀▀▜▖
▝▜▌ █ ▐▛▘
 ▝▀▀▀▀▀▘
"""

antigravity = """
 ▗▛▀▀▀▜▖
▐█ ◆ ◆ █▌
 ▝▀▀▀▀▀▘
"""

cursor = """
 ▗▛▀▀◢█▖
▐█ ▘ ▝▜█▌
 ▝▀▀◢█▀▘
"""

kimi = """
 ▐█▛█▛█▌
 ▐█████▌
"""

droid = """
 ▘▐███▌▝
▐█ ▖ ▗ █▌
 ▝▀▀▀▀▀▘
"""

copilot = """
 ▗█████▖
▐█ ▘ ▝ █▌
  ▔▔▔▔▔
"""

kiro = """
 ▗▛▀▀▀▜▖
▐█ ▘ ▘ █▌
 ▝▘▝▘▝▘
"""

qwen = """
 ▐▀▀▀▀▀▌
▐█ ▘ ▘ █▌
 ▝▀▀▀▀▀▘
"""

fallback = [
"""
 ▐▛▀▀▀▜▌
▝▜█▘ ▝█▛▘
 ▝▘   ▝▘
""",
"""
 ▗▛███▜▖
▐█ ▀▀▀ █▌
 ▝▀▀▀▀▀▘
""",
"""
 ▗▛▀▀▀▜▖
▐█ ▘ ▝ █▌
 ▝▘▝▀▘▝▘
""",
"""
 ▐▀▀▀▀▀▌
▐█ ▬ ▬ █▌
 ▝▀▀▀▀▀▘
""",
"""
 ✦▐███▌✦
▐█ ▄ ▄ █▌
 ▝▀▀▀▀▀▘
""",
"""
 ▗▛✦▀✦▜▖
▐█ ▘ ▝ █▌
 ▝▘▝▀▘▝▘
""",
"""
 ▗▛▀▀▀▜▖
▐▛ ▘ ▝ ▜▌
 ▝▘▝ ▘▝▘
""",
"""
 ▘▐███▌▝
▐█ ▪ ▪ █▌
 ▝▘▀▀▀▝▘
""",
"""
 ▗█████▖
▐█ ▄ ▄ █▌
 ▝▀▀▀▀▀▘
"""
]
