//! The team prompt layer: the consensus and team-level prompt files a staged
//! team composes after every role's own system prompt, and the inspection
//! copy of the built-in consensus RimZ publishes beside the team definitions.

use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::config::Team;

/// The consensus every staged team runs under unless `consensus-file` replaces it.
pub const BUILT_IN_CONSENSUS: &str = include_str!("team_consensus.md");

/// Where the inspection copy of [`BUILT_IN_CONSENSUS`] lives under
/// `agents_home`. The team definitions loader skips this path, so no Markdown
/// team can be named `consensus`.
pub fn consensus_copy_path(agents_home: &Path) -> PathBuf {
    agents_home.join("teams").join("consensus.md")
}

/// Publish the read-only inspection copy of the embedded consensus. Nothing
/// reads the file back: teams always run under [`BUILT_IN_CONSENSUS`], so the
/// copy is generated output and rewriting a stale or edited one loses nothing.
/// Returns the path when it wrote, `None` when the copy was already current.
pub fn publish_consensus_copy(
    agents_home: &Path,
) -> Result<Option<PathBuf>, crate::disk::atomic::AtomicErr> {
    let path = consensus_copy_path(agents_home);
    let bytes = consensus_copy_text();
    if std::fs::read(&path).is_ok_and(|current| current == bytes.as_bytes()) {
        return Ok(None);
    }
    crate::disk::atomic::write_bytes_atomically(&path, bytes.as_bytes())?;
    Ok(Some(path))
}

fn consensus_copy_text() -> String {
    format!(
        "<!-- Generated by rimz {}. A read-only copy of the built-in team consensus: \
         RimZ never reads this file, so edits change nothing and are overwritten. \
         To replace it, set `consensus-file` on a project TOML team. -->\n\n{BUILT_IN_CONSENSUS}",
        crate::build_id::VERSION
    )
}

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Consensus {
    BuiltIn,
    File(PathBuf),
}

/// Composed after the role's base prompt and fragments, in field order.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct TeamPrompt {
    pub consensus: Consensus,
    pub files: Vec<crate::config::PromptSource>,
}

impl TeamPrompt {
    /// The layer one role of `team` receives. Replacement is the only typed
    /// prompt channel, so a role without a base prompt receives none; an
    /// unstaged team has no pipeline for a consensus to govern.
    pub(super) fn for_role(team: &Team, role_has_base: bool) -> Option<Self> {
        (team.staged() && role_has_base).then(|| Self {
            consensus: team
                .consensus_file
                .clone()
                .map_or(Consensus::BuiltIn, Consensus::File),
            files: team.append_system_prompt_files.clone(),
        })
    }
}

/// Whether the team configures its layer explicitly, which makes an
/// undeliverable layer a refusal instead of a silent omission.
pub(super) fn declared(team: &Team) -> bool {
    team.consensus_file.is_some() || !team.append_system_prompt_files.is_empty()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn consensus_copy_writes_once_and_repairs_edits() {
        let home = tempfile::tempdir().unwrap();
        let path = consensus_copy_path(home.path());
        assert_eq!(
            publish_consensus_copy(home.path()).unwrap(),
            Some(path.clone())
        );
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.starts_with("<!-- Generated by rimz "), "{text}");
        assert!(text.ends_with(BUILT_IN_CONSENSUS));
        assert_eq!(publish_consensus_copy(home.path()).unwrap(), None);
        std::fs::write(&path, "edited").unwrap();
        assert_eq!(
            publish_consensus_copy(home.path()).unwrap(),
            Some(path.clone())
        );
        assert_eq!(std::fs::read_to_string(&path).unwrap(), text);
    }
}
