//! Canned pet captions keyed by attention-action transitions.

use super::model::PetAction;

/// A canned line for the pet to "say" when the selected-card action changes,
/// drawn from the matching pool by `seed` so repeated transitions vary. Returns
/// `None` while the action holds, so a line shows once per change and the prior
/// line keeps standing. `pool[0]` is the plain line; later entries add variety.
pub(crate) fn caption(
    previous: Option<PetAction>,
    current: PetAction,
    seed: u64,
) -> Option<&'static str> {
    if previous == Some(current) {
        return None;
    }
    let pool = match current {
        PetAction::Ask => ASK,
        PetAction::Failed => FAILED,
        PetAction::Thinking => THINKING,
        PetAction::Running => RUNNING,
        PetAction::Waiting => WAITING,
        PetAction::Review => REVIEW,
        PetAction::Idle => match previous {
            Some(
                PetAction::Ask
                | PetAction::Failed
                | PetAction::Thinking
                | PetAction::Running
                | PetAction::Waiting
                | PetAction::Review,
            ) => CAUGHT_UP,
            _ => RESTING,
        },
    };
    Some(pool[(seed as usize) % pool.len()])
}

// Every pool keeps its lines glanceable: at most 26 columns, ascii,
// lowercase, unique across all pools. The tests module enforces all of it.

const ASK: &[&str] = &[
    "someone needs you",
    "your turn",
    "tap in - you're up",
    "an agent's waiting",
    "psst, over here",
    "question at the door",
    "one answer, please",
    "a hand is raised",
    "the floor is yours",
    "decision time",
    "quick question inbound",
    "someone said your name",
    "eyes on you, boss",
    "it's for you",
    "the room wants a word",
    "human required",
    "one nod unblocks it",
    "an agent taps its foot",
    "waving you down",
    "green light needed",
    "rubber stamp, please",
    "a yes or no would do",
    "your call to make",
    "somebody's stuck on you",
    "a prompt awaits its human",
    "knock knock - it's work",
    "small ask, big unblock",
    "the queue paused for you",
    "one keypress frees them",
    "an agent left you a note",
    "this one wants a human",
    "help a bot out?",
    "your wisdom, please",
    "tiny decision ahead",
    "the pane calls your name",
    "incoming question",
    "a bot craves guidance",
    "stuck until you say go",
    "permission slip needed",
    "sign here, please",
    "one agent, hand raised",
    "they can't pick for you",
    "a crossroads needs you",
    "the baton is yours",
    "answer to continue",
    "someone's holding breath",
    "your move, human",
    "waving with both paws",
    "a card turned to you",
    "it needs a human touch",
    "pick a lane for them",
    "quick sanity check?",
    "an ask just landed",
    "bot to human: come in",
    "paging the human",
    "the fleet looks to you",
    "one question in the air",
    "don't leave them hanging",
    "a verdict is wanted",
    "yes, no, or maybe?",
    "approval wanted",
    "work waits on a word",
    "drop by that pane",
    "an agent wrote you first",
    "it's blocking on you",
    "jump in when ready",
    "the cursor parks on you",
    "they saved you a seat",
    "only you can pick this",
    "free them with one line",
    "the ask light is on",
    "someone rang the bell",
    "mail for the human",
    "one click from progress",
    "the agent said please",
    "waiting on your ruling",
    "speak and they resume",
    "a thread wants your take",
    "flag raised in the room",
    "your two cents, please",
    "bots can't sign for you",
    "a question mark glows",
    "so close - just say go",
    "this pane misses you",
    "human input required",
    "one answer, then zoom",
    "they asked so nicely",
    "wave back when you can",
    "don't ghost the bot",
    "an agent knocked twice",
    "help wanted: you",
    "the plan needs a blessing",
    "a checkpoint wants you",
    "tag - you're it",
    "one word gets them going",
    "verdict, please",
    "they hit the human step",
    "an agent seeks counsel",
    "this fork is yours",
    "the room paused politely",
    "someone requests an ear",
    "lend them a decision",
    "holler back, boss",
    "a paw points at you",
    "answer at your leisure",
    "you hold the gate key",
    "tiny ask, honest",
    "a bot awaits your nod",
    "your seal of approval?",
    "the next step is yours",
    "inbox has a live one",
    "take the mic",
    "one human moment, please",
    "they need the boss key",
    "you're the unblock",
    "a choice sits waiting",
    "ping! that's you",
    "the turn needs a pilot",
    "reply when you're ready",
    "all it takes is a word",
];

const FAILED: &[&str] = &[
    "rough patch - take a look",
    "something's stuck",
    "hit a snag",
    "we're wedged here",
    "this one needs a nudge",
    "that turn fell over",
    "gremlins in the gears",
    "it face-planted, sorry",
    "red light on the board",
    "that didn't stick",
    "the wheels came off",
    "a turn went sideways",
    "it tripped on a root",
    "stuck in the mud",
    "that run keeled over",
    "sparks, the bad kind",
    "a hiccup with teeth",
    "the build bit back",
    "plan met reality, lost",
    "that one's belly-up",
    "a snag wants a human",
    "it stubbed a paw",
    "crash landing, soft-ish",
    "the turn gave up",
    "something went sproing",
    "needs a human mechanic",
    "it's sulking in a corner",
    "error ate the homework",
    "down but not out",
    "that swing missed",
    "oof - error town",
    "the pipeline coughed",
    "a test bared its fangs",
    "it painted itself in",
    "bonk - wall found",
    "the happy path wasn't",
    "a knot needs untying",
    "this needs your wrench",
    "it went pear-shaped",
    "failure, dramatically so",
    "the turn ran aground",
    "shipwreck in a teacup",
    "a bug won this round",
    "it hit an invisible wall",
    "that command backfired",
    "smoke, but no fire yet",
    "the retry gave up too",
    "it's stuck in a loop",
    "a stack trace blooms",
    "the exit code frowned",
    "nonzero exit, long face",
    "that turn needs cpr",
    "gravity won this one",
    "the diff fought back",
    "it dropped the baton",
    "a segfault of the soul",
    "flat tire on the fast lane",
    "tools down, help needed",
    "the run tapped out",
    "an error did a cartwheel",
    "that didn't compile, huh",
    "broke in a new place",
    "same wall, new dent",
    "the machine said no",
    "computer says no again",
    "it needs a fresh start",
    "a restart might help",
    "send snacks and a fix",
    "the turn lost its keys",
    "progress: interrupted",
    "it fumbled the handoff",
    "the script went rogue",
    "one step forward, crash",
    "tangled in its own yarn",
    "the lane hit a pothole",
    "debris on the runway",
    "it bounced off the gate",
    "a red x moved in",
    "the job pulled a muscle",
    "mission paused by chaos",
    "it choked on a comma",
    "syntax had other plans",
    "the parser disagreed",
    "a typo with ambitions",
    "the test suite growled",
    "ci threw a tantrum",
    "it tripped over a flag",
    "the branch bit the dust",
    "merge conflict, feelings",
    "rebase went feral",
    "the socket hung up",
    "timeout took the wheel",
    "a deadline came armed",
    "the api said nope",
    "rate limit, meet wall",
    "it lost a staring match",
    "the disk said enough",
    "permission denied, rude",
    "path not found, drama",
    "null showed up again",
    "off by one, off by lots",
    "the cache lied",
    "stale state strikes",
    "a race condition raced",
    "the lock never opened",
    "it panicked, literally",
    "unwrap met its none",
    "the queue jammed",
    "a zombie process groans",
    "the pane went quiet",
    "it needs a grown-up",
    "poke it and see",
    "a gentle kick may fix it",
    "worth a second look",
    "logs hold the story",
    "the trail ends here",
    "this knot's above my paws",
    "i tried barking at it",
    "even the pet is worried",
    "we'll get 'em next turn",
];

const THINKING: &[&str] = &[
    "thinking it through",
    "reading the room",
    "working it out",
    "still reasoning",
    "mapping the path",
    "gears are turning",
    "plotting the route",
    "deep in thought",
    "chewing on the problem",
    "big brain hours",
    "connecting the dots",
    "pacing and pondering",
    "hmm, and again hmm",
    "weighing the options",
    "sketching a plan",
    "brewing an idea",
    "thoughts loading",
    "squinting at the problem",
    "lining up dominoes",
    "tracing the threads",
    "measuring twice",
    "simmering on it",
    "the plot thickens",
    "turning it over",
    "considering everything",
    "brain at full hum",
    "reading between lines",
    "counting the branches",
    "what if... what if...",
    "following a hunch",
    "chasing an idea's tail",
    "thinking cap: on",
    "deep dive in progress",
    "spelunking the codebase",
    "mulling it over",
    "hypothesis brewing",
    "crunching the angles",
    "the wheels spin quietly",
    "quiet, genius at work",
    "plan hatching",
    "scheming (nicely)",
    "strategy in the oven",
    "one step ahead, maybe",
    "exploring the maze",
    "sniffing out the path",
    "ears up, mind busy",
    "tail still, brain loud",
    "puzzling it out",
    "rearranging the pieces",
    "hunting the root cause",
    "peering down rabbit holes",
    "so many branches",
    "thinking in graphs",
    "logic knitting",
    "assembling the argument",
    "drawing the map",
    "brainstorm in a teacup",
    "pondering, professionally",
    "a thought takes shape",
    "the idea is loading",
    "rummaging through notes",
    "flipping through memory",
    "cross-checking the facts",
    "reading the fine print",
    "double-checking the math",
    "quiet cogs, loud ideas",
    "inventing option three",
    "ruling things out",
    "narrowing the search",
    "the hunch grows stronger",
    "eyes closed, computing",
    "tokens well spent",
    "thinking real hard",
    "galaxy brain warming up",
    "dot dot dot",
    "processing... politely",
    "it's all coming together",
    "threads being untangled",
    "sorting signal from noise",
    "framing the problem",
    "asking the right question",
    "what would rust do?",
    "reasoning at full tilt",
    "mind palace under way",
    "pacing the same tile",
    "left, right, left again",
    "walking the problem off",
    "circling the answer",
    "the answer is close",
    "almost has it",
    "on the scent",
    "warm... warmer...",
    "an aha approaches",
    "lightbulb flickering",
    "sparks upstairs",
    "synapses doing laps",
    "thoughts at a gallop",
    "slow is smooth here",
    "smooth is fast, right?",
    "deep focus mode",
    "do not disturb: thinking",
    "quiet please, plotting",
    "head down, mind up",
    "brains before keystrokes",
    "plan first, type later",
    "the design phase hums",
    "drafting in its head",
    "consulting the void",
    "consulting the docs",
    "weighing the tradeoffs",
    "picking the right tool",
    "choosing its battles",
    "the puzzle stares back",
    "thinking outside the pane",
    "pondering the edge cases",
    "edge cases everywhere",
    "what about timezones?",
    "naming things is hard",
    "cache or invalidate?",
    "one more think, promise",
];

const RUNNING: &[&str] = &[
    "room is moving",
    "things are humming",
    "work in flight",
    "cooking with gas",
    "hands are busy",
    "full steam ahead",
    "zoomies, productive ones",
    "keys are clacking",
    "code is flowing",
    "wheels turning fast",
    "making tracks",
    "progress in motion",
    "the fleet is rolling",
    "shipping mode: on",
    "busy paws at work",
    "diffs are landing",
    "edits in the air",
    "tokens are flying",
    "the lane is live",
    "green lights all the way",
    "building at pace",
    "brick by brick",
    "line by line",
    "commit by commit",
    "steady hands, fast keys",
    "work hums along",
    "the engine purrs",
    "throttle open",
    "cruising speed",
    "in the zone",
    "flow state achieved",
    "don't blink, it's fast",
    "watch it go",
    "look at 'em go",
    "vroom, basically",
    "running like the wind",
    "a blur of keystrokes",
    "productivity noises",
    "busy in the best way",
    "heads down, speed up",
    "the sprint is sprinting",
    "laps around the codebase",
    "eating tasks for lunch",
    "tasks falling like pins",
    "checkboxes, beware",
    "the todo list shrinks",
    "crossing things off",
    "one down, more to go",
    "chipping away nicely",
    "hammering it out",
    "forging ahead",
    "carving through it",
    "slicing through the work",
    "the keyboard sings",
    "sparks of progress",
    "hot keys, literally",
    "cooking something good",
    "the oven is on",
    "stirring the pot, fast",
    "whisking up changes",
    "fresh code, coming up",
    "order up: more code",
    "output in progress",
    "bytes on the move",
    "electrons earning keep",
    "cpu doing cardio",
    "fans may spin up",
    "the pane scrolls fast",
    "logs racing by",
    "text waterfall engaged",
    "words per minute: many",
    "it types faster than me",
    "faster than my zoomies",
    "i can barely keep up",
    "running alongside",
    "jogging beside the work",
    "keeping pace nicely",
    "smooth and steady",
    "no bumps so far",
    "clean laps so far",
    "lap after lap",
    "mile after mile",
    "onward and onward",
    "momentum is real",
    "rolling downhill nicely",
    "gaining ground",
    "covering ground fast",
    "terrain: conquered",
    "path clear, speed up",
    "open road ahead",
    "wind in the fur",
    "ears back, full speed",
    "tail out, torque up",
    "paws barely touch ground",
    "leaving dust behind",
    "catch me if you can",
    "beep beep, coming through",
    "on a roll",
    "hot streak going",
    "the streak continues",
    "nothing can stop this",
    "unstoppable-ish",
    "quietly crushing it",
    "crushing it, humbly",
    "work goes brrr",
    "compilers go brrr",
    "the grind is grinding",
    "good hustle out there",
    "hustle with a smile",
    "all cylinders firing",
    "engines at eleven",
    "warp speed, engage",
    "ludicrous speed soon",
    "turbo mode found",
    "overdrive engaged",
    "shipping season",
    "progress bar climbing",
    "numbers going up",
    "green diffs everywhere",
    "busy room, happy pet",
];

const WAITING: &[&str] = &[
    "waiting on work",
    "background work",
    "standing by",
    "holding the line",
    "watching the lane",
    "patience mode: on",
    "the kettle is on",
    "subagents on the case",
    "minions are digging",
    "helpers doing the legwork",
    "delegation in action",
    "the crew is out working",
    "waiting on the runners",
    "runners still running",
    "results due back soon",
    "out for a fetch",
    "fetch in progress",
    "waiting for the echo",
    "line cast, rod steady",
    "fishing for results",
    "watching the bobber",
    "eyes on the horizon",
    "scanning the horizon",
    "any minute now",
    "soon, probably",
    "it'll be back",
    "they always come back",
    "holding the fort",
    "keeping the seat warm",
    "saving their spot",
    "the bench is warm",
    "warming the bench",
    "on standby",
    "idling with intent",
    "engine idling, warm",
    "paused, not stopped",
    "a strategic pause",
    "resting between reps",
    "between innings",
    "halftime for the turn",
    "intermission",
    "the clock ticks softly",
    "counting ceiling tiles",
    "humming quietly",
    "whistling, waiting",
    "twiddling my paws",
    "tapping the counter",
    "checking the mailbox",
    "mailbox checked: empty",
    "refresh... refresh...",
    "f5 energy",
    "watching the spinner",
    "the spinner spins",
    "loading, but elsewhere",
    "work happens off-screen",
    "off doing homework",
    "the oven timer's set",
    "dough is rising",
    "marinating",
    "letting it steep",
    "tea's not ready yet",
    "slow-cooking progress",
    "good things take time",
    "rome wasn't built async",
    "async and i know it",
    "awaiting the await",
    "promise still pending",
    "futures being polled",
    "polling politely",
    "the queue moves quietly",
    "in line, holding snacks",
    "holding ticket 42",
    "deli counter vibes",
    "rate limit nap time",
    "budget window breathing",
    "tokens recharging",
    "mana regenerating",
    "cooldown in progress",
    "recharging the lasers",
    "batteries topping up",
    "the meter refills",
    "sand through the glass",
    "hourglass duty",
    "the window reopens soon",
    "back when limits lift",
    "provider says soon",
    "waiting out the weather",
    "riding out the 429s",
    "clouds will pass",
    "the tide will turn",
    "watering the plants",
    "window-watching",
    "birdwatching till ready",
    "cloud-gazing on shift",
    "guard duty, quiet shift",
    "night watch, all calm",
    "sentry mode",
    "periscope up",
    "ears perked for news",
    "one ear on the wire",
    "listening for footsteps",
    "waiting by the door",
    "nose to the window",
    "tail set to slow wag",
    "sit and stay, expertly",
    "professional waiting",
    "waiting: nailed it",
    "certified lurker",
    "lurking productively",
    "patience is my cardio",
];

const REVIEW: &[&str] = &[
    "reviewing context",
    "condensing context",
    "tidying memory",
    "making room",
    "compressing notes",
    "folding clean laundry",
    "squeezing the sponge",
    "wringing out the context",
    "trimming the transcript",
    "pruning old branches",
    "raking the leaves",
    "sweeping the floors",
    "dusting the shelves",
    "vacuuming the context",
    "spring cleaning",
    "tidy pane, tidy mind",
    "a tidy mind works better",
    "decluttering thoughts",
    "marie kondo mode",
    "does this spark joy?",
    "keeping the good parts",
    "saving the highlights",
    "highlights only, please",
    "summarizing the saga",
    "the recap episode",
    "previously, on this turn",
    "shortening the story",
    "abridging the epic",
    "condensing the lore",
    "lore compression",
    "archiving the scrolls",
    "rolling up the scrolls",
    "filing the paperwork",
    "paperwork, but fast",
    "stapling thoughts together",
    "zipping up memories",
    "compressing the chronicle",
    "squashing the history",
    "rebasing its memories",
    "garbage collecting",
    "taking out the trash",
    "emptying the recycle bin",
    "clearing the cache",
    "defragging the brain",
    "tuning up the memory",
    "memory diet in progress",
    "context on a diet",
    "slimming the context",
    "shedding old tokens",
    "token budget rescue",
    "making headroom",
    "clearing the runway",
    "clearing desk space",
    "making space to think",
    "room for new ideas",
    "fresh space incoming",
    "new context, who dis",
    "packing light",
    "repacking the bags",
    "downsizing the luggage",
    "luggage fees avoided",
    "carry-on only",
    "distilling the essence",
    "boiling it down",
    "reducing the sauce",
    "sauce reduction hour",
    "essence, extracted",
    "keeping the tl;dr",
    "tl;dr in progress",
    "writing the cliff notes",
    "margin notes only",
    "index cards, sorted",
    "reshelving the books",
    "library quiet hours",
    "shushing old chatter",
    "muting stale threads",
    "pruning dead ends",
    "weeding the garden",
    "deadheading old blooms",
    "compost for old context",
    "mulching the transcript",
    "tidying the yarn ball",
    "untangling, then coiling",
    "coiling the rope neatly",
    "folding the map smaller",
    "the map folds neatly",
    "squeezing into one page",
    "one page, all signal",
    "signal kept, noise out",
    "noise: escorted out",
    "history, but curated",
    "curating the memories",
    "memory lane, repaved",
    "fresh notebook feeling",
    "sharpening the pencils",
    "resetting the desk",
    "clean slate, almost",
    "brain broom at work",
    "small context, big brain",
    "lighter already",
];

const CAUGHT_UP: &[&str] = &[
    "all caught up",
    "inbox zero",
    "nothing left to chase",
    "clear skies",
    "good as done",
    "the board is green",
    "queue empty, heart full",
    "nothing needs you",
    "all quiet, all good",
    "every card is calm",
    "fleet at ease",
    "mission complete",
    "victory lap time",
    "take the win",
    "that's a wrap",
    "ship it and smile",
    "done and dusted",
    "crossed the last t",
    "dotted the last i",
    "the list is empty",
    "todo: nothing",
    "zero pending, zero drama",
    "no news is good news",
    "silence, the good kind",
    "peace in the panes",
    "panes at peace",
    "the room exhales",
    "deep breath, all clear",
    "smooth sailing achieved",
    "harbor reached",
    "anchored and happy",
    "the dust has settled",
    "dust settled, work done",
    "all threads tied",
    "loose ends: none",
    "knots all untied",
    "everything's landed",
    "all diffs at rest",
    "commits tucked in",
    "branches sleeping soundly",
    "ci is green and gleaming",
    "tests pass, birds sing",
    "green checks everywhere",
    "checkmarks to the horizon",
    "gold stars all around",
    "high paws, everyone",
    "treats well earned",
    "treat yourself",
    "snack break earned",
    "stretch break earned",
    "you've earned a coffee",
    "coffee break approved",
    "tea time, guilt-free",
    "go touch some grass",
    "grass touching time",
    "sun's out, work's done",
    "clock out proudly",
    "nothing on fire",
    "zero fires today",
    "the pager is silent",
    "no alarms, no surprises",
    "calm seas, full sails",
    "flat water ahead",
    "cruise control",
    "coasting, deservedly",
    "glide mode",
    "nothing to fix",
    "nothing to fetch",
    "chase list empty",
    "caught up and cozy",
    "cozy status: achieved",
    "comfy and complete",
    "satisfaction: 100%",
    "progress bar: full",
    "100% synced",
    "everything reconciled",
    "ledger balanced",
    "books closed happily",
    "desk is clear",
    "clean desk, clear mind",
    "whiteboard wiped",
    "chalk dust settled",
    "pencils down",
    "tools hung up neatly",
    "workshop swept",
    "the forge cools gently",
    "embers, not fires",
    "quiet engine, warm heart",
    "idle by choice now",
    "earned this idle",
    "proud of the fleet",
    "the fleet did great",
    "good bots, all of them",
    "everyone did the thing",
    "team effort, team win",
    "gg everyone",
    "and... scene",
    "curtain call",
    "standing ovation",
    "take a bow, fleet",
    "roll the credits",
    "end of episode",
    "to be continued...",
    "same time tomorrow?",
    "what's next, boss?",
    "ready for the next quest",
    "side quests: cleared",
    "main quest: complete",
    "save point reached",
    "game saved, go play",
];

const RESTING: &[&str] = &[
    "resting",
    "taking a nap",
    "stretching out",
    "keeping watch",
    "just vibing",
    "curled up comfy",
    "snoozing lightly",
    "one eye open",
    "daydreaming",
    "loafing, expertly",
    "bread loaf position",
    "paws tucked in",
    "tail over nose",
    "sunbeam acquired",
    "found a warm spot",
    "warm keyboard, warm nap",
    "do not disturb-ish",
    "five more minutes",
    "quiet hours",
    "low power mode",
    "sleep mode, kind of",
    "screensaver brain",
    "idle animation irl",
    "ambient purring",
    "purring at 60hz",
    "soft snores",
    "dreaming of green diffs",
    "dreaming in pixels",
    "counting sleepy commits",
    "counting electric sheep",
    "recharging the cute",
    "recharging, no rush",
    "topping up energy",
    "storing up zoomies",
    "saving energy for later",
    "energy: conserving",
    "hibernation lite",
    "shallow hibernation",
    "cat nap protocol",
    "power nap engaged",
    "micro-nap in progress",
    "blinking real slow",
    "slow blinks for you",
    "yawn... hi",
    "stretch, yawn, repeat",
    "big stretch",
    "another glorious stretch",
    "toe beans airing out",
    "belly up, trust achieved",
    "flopped over",
    "maximum flop",
    "gravity nap",
    "melted into the floor",
    "puddle of pet",
    "cozy blob mode",
    "blanket fort hours",
    "nest built, occupied",
    "burrowed in",
    "den sweet den",
    "home is this corner",
    "this corner is mine now",
    "guarding the dashboard",
    "guarding you, quietly",
    "on lazy patrol",
    "patrol postponed",
    "watch duty, horizontal",
    "horizontal and proud",
    "professionally idle",
    "idle, but adorable",
    "decorative mode",
    "mascot duties only",
    "moral support mode",
    "emotional support pixel",
    "support pixel on duty",
    "vibes: mellow",
    "mellow to the max",
    "chill level: expert",
    "certified chill",
    "zen achieved",
    "inner peace found",
    "meditating, probably",
    "contemplating the cursor",
    "watching the cursor blink",
    "cursor hypnosis",
    "lava lamp brain",
    "thoughts on shuffle",
    "humming to the fans",
    "listening to fan hum",
    "white noise enjoyer",
    "rain sounds optional",
    "cloud watching indoors",
    "window seat secured",
    "birds outside, noted",
    "squirrel! ...never mind",
    "chasing dream squirrels",
    "dream zoomies only",
    "running in my sleep",
    "twitchy sleep paws",
    "sleepy but standing by",
    "half asleep, half alert",
    "ready if you need me",
    "call me if things move",
    "wake me for action",
    "poke me when busy",
    "i'll be right here",
    "holding down the couch",
    "couch security detail",
    "off the clock",
    "clocked out, curled up",
    "sweet dreams, fleet",
];

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// Captions sit in a one-line sliver beside the sprite; past this width
    /// they stop reading at a glance.
    const CAPTION_MAX_WIDTH: usize = 26;

    const POOLS: &[(&str, &[&str])] = &[
        ("ask", ASK),
        ("failed", FAILED),
        ("thinking", THINKING),
        ("running", RUNNING),
        ("waiting", WAITING),
        ("review", REVIEW),
        ("caught_up", CAUGHT_UP),
        ("resting", RESTING),
    ];

    #[test]
    fn captions_fire_on_action_transitions() {
        assert_eq!(
            caption(Some(PetAction::Running), PetAction::Ask, 0),
            Some("someone needs you")
        );
        assert_eq!(
            caption(Some(PetAction::Ask), PetAction::Idle, 0),
            Some("all caught up")
        );
        assert_eq!(caption(None, PetAction::Idle, 0), Some("resting"));
        assert_eq!(caption(Some(PetAction::Idle), PetAction::Idle, 7), None);
    }

    #[test]
    fn seed_varies_the_line_within_a_pool() {
        let first = caption(None, PetAction::Running, 0);
        let second = caption(None, PetAction::Running, 1);
        assert!(first.is_some() && second.is_some());
        assert_ne!(first, second, "different seeds pick different lines");
    }

    #[test]
    fn every_pool_offers_deep_variety() {
        for (name, pool) in POOLS {
            assert!(
                pool.len() >= 100,
                "{name}: pool holds {} lines, wants at least 100",
                pool.len()
            );
        }
    }

    /// Ascii keeps `len()` equal to column width, so the width assert is the
    /// on-screen budget.
    #[test]
    fn every_line_reads_at_a_glance() {
        for (name, pool) in POOLS {
            for line in *pool {
                assert!(line.is_ascii(), "{name}: {line:?} stays ascii");
                assert!(
                    !line.is_empty() && line.trim() == *line,
                    "{name}: {line:?} keeps no edge whitespace"
                );
                assert!(
                    line.len() <= CAPTION_MAX_WIDTH,
                    "{name}: {line:?} is {} cols, max {CAPTION_MAX_WIDTH}",
                    line.len()
                );
                assert!(
                    !line.chars().any(|c| c.is_ascii_uppercase()),
                    "{name}: {line:?} stays lowercase"
                );
                assert!(!line.contains("  "), "{name}: {line:?} keeps single spaces");
            }
        }
    }

    #[test]
    fn every_line_is_unique_across_pools() {
        let mut seen: BTreeMap<&str, &str> = BTreeMap::new();
        for (name, pool) in POOLS {
            for line in *pool {
                if let Some(other) = seen.insert(line, name) {
                    panic!("{line:?} appears in both {other} and {name}");
                }
            }
        }
    }
}
